apiVersion: v1
data: {}
kind: Secret
metadata:
  name: alertmanager-main
stringData:
  alertmanager.yaml: |-
    "global":
      "resolve_timeout": "2m"
    "inhibit_rules":
    - "equal":
      - "alertname"
      "source_match":
        "severity": "critical"
      "target_match_re":
        "severity": "warning|info"
    - "equal":
      - "alertname"
      "source_match":
        "severity": "warning"
      "target_match_re":
        "severity": "info"
    "receivers":
    - "name": "Default"
    - "name": "executor"
      "webhook_configs": 
      - "url": "http://172.16.17.100:31000"
    - "name": "Critical"
    "route":
      "group_by":
      - "namespace"
      "group_interval": "20s"
      "group_wait": "10s"      
      "repeat_interval": "10s"
      "receiver": "Default"
      "routes":
      - "match":
          "alertname": "example-alert"
        "receiver": "executor"
      - "match":
          "severity": "critical"
        "receiver": "Critical"
type: Opaque