apiVersion: v1
data: {}
kind: Secret
metadata:
  name: alertmanager-main
  namespace: monitoring
stringData:
  alertmanager.yaml: |-
  "global":
    "smtp_smarthost": "mail.example.com:25"
    "smtp_from": "prometheus@example.com"

  "route":
    "receiver": "default"
    "routes":
    - "receiver": "executor"
      "match":
        "alertname": "example-alert"

  "receivers":
  - "name": "default"
    "email_configs":
    - "to": "ops@example.com"

  - "name": 'executor'
    "webhook_configs":
    - "url": "http://172.16.17.100:31000"
  type: Opaque